### ISSUE TITLE
Update Color Unit Tests to Test Color Creation with Hex Strings

### ISSUE THREAD

**Issue by blwatkins** [brittni-and-the-polar-bear/generative-art-library_base#2]
# Description

Unit tests for the Color class need to be updated to test that they behave properly when built from a color created with a hexadecimal color string.

# Tasks
- [x] color from hex string constructor
- [x] color from hex string setter method
- [ ] color from invalid hex string constructor
- [ ] color from invalid hex string setter method
