### ISSUE TITLE
Investigation: How Does Not Minifying Code Improve Socket Score? 

### ISSUE THREAD

**Issue by blwatkins** [brittni-and-the-polar-bear/generative-art-library_base#42]
# Description

If we do not minify the library with Terser, how much does that improve our [Socket](https://socket.dev/npm/package/@batpb/genart-base) score.

If we see a significant improvement, we will remove minifying from all libraries. This will mean that the color and palette libraries will need to be split up.

# Tasks

- [x] record current Socket score (score = 58)
- [x] record current bundle size (size = 64.3 KB)
- [x] remove terser and minifying from library
- [x] release a new version
- [x] wait for Socket score to be calculated
- [x] record new Socket score (score = 53)

## If significant improvement

- [ ] remove terser dependency from `package.json`
- [ ] create issues to remove dependency from other library packages
